name = "jec-esports-hub"
main = "dist/worker.js"
compatibility_date = "2024-07-25"

[site]
bucket = "./dist"
name = "jec-esports-hub"
main = "dist/worker.js" # Placeholder for a potential worker script
compatibility_date = "2024-07-25"

[site]
bucket = "./dist"
